### ISSUE TITLE
errors in setup/install

### ISSUE THREAD

**Issue by emmakat** [git-developer/marvyn#1]
Hi! 
When I attempt to follow the tl:dr instructions, and run `wget -O - https://github.com/git-developer/marvyn/tarball/develop | tar --one-top-level=/opt/docker/marvyn --strip-components 1 -xz`
 I get many errors. I've also tried with sudo and it didn't help.

tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/LICENSE: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/README.keys: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/README.md: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/.start: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/remux-directory: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/rip-disc: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/transcode-audio-directory: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/transcode-disc-directory: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/transcode-series-directory: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/bin/vaapi-transcode: Cannot create symlink to ‘.start’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/data: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/data/.abcde.conf: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/base.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/mail.env: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/remux-directory.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/rip-disc.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/transcode-audio-directory.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/transcode-disc-directory.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/transcode-series-directory.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/etc/vaapi-transcode.yml: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/.image-metadata: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/Dockerfile: Cannot create symlink to ‘Dockerfile.ubuntu’: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/Dockerfile.debian: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/Dockerfile.ubuntu: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/build: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/build-with-metadata: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/image/patch-abcde: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/.prepare: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/makemkvcon: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/remux-directory: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/rip-disc: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/transcode-audio-directory: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/transcode-disc-directory: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/transcode-series-directory: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/services/vaapi-transcode: Cannot open: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/udev: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/udev/rules.d: Cannot mkdir: No such file or directory
tar: /opt/docker: Cannot mkdir: Permission denied
tar: /opt/docker/marvyn/udev/rules.d/disc-detection.rules: Cannot open: No such file or directory
tar: Exiting with failure status due to previous error

**Comment by git-developer** [comment]
Looks like your user account does not have write access to `/opt`. You could either set appropriate permissions or run the `tar` command with a privileged account.

**Comment by emmakat** [comment]
thank you!
