### ISSUE TITLE
cannot set niceness

### ISSUE THREAD

**Issue by emmakat** [git-developer/marvyn#11]
Small issue - I tried to set the niceness to -10 but i get an error 
nice: cannot set niceness: Permission denied

I researched this error and found:   A negative niceness (priority increase) requires additional permissions. In this case, the container should be run with the docker option --cap-add=SYS_NICE

I am not sure how to fix this for Marvyn though. Thanks for any insight you may have.

**Comment by git-developer** [comment]
The permission may be added in the configuration file where you define the niceness value. Example:
```yaml
    environment:
      - MARVYN_NICENESS=-10
    cap_add:
      - SYS_NICE
```
See the [docker-compose docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#cap_add-cap_drop) for details on the syntax.

Please report back if this proposal fixes your issue.

**Comment by emmakat** [comment]
thank you! I'll try it today and report back/close the issue. If it does solve it, I'll send a PR to add to the readme

**Comment by git-developer** [comment]
Well, it has a reason that negative niceness requires extra capabilities, and I don't want to recommend doing this for general use. When you decide to use such a priority, you should know the consequences and - in my opinion - you should know the syntax, too. The syntax is not specific to MARVYN but common to all docker compose applications.

**Comment by emmakat** [comment]
ah, good point. I'll keep this in my repo for now.
