### ISSUE TITLE
cannot stat 'marvyn/opt/docker/marvyn': no such file or directory

### ISSUE THREAD

**Issue by emmakat** [git-developer/marvyn#2]
attempting installation instructions and no matter what I do, where I do it, always getting this error:

/opt/docker$ sudo git clone --depth 1 https://github.com/git-developer/marvyn
Cloning into 'marvyn'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 39 (delta 0), reused 24 (delta 0), pack-reused 0
Unpacking objects: 100% (39/39), done.
jd@jd-OptiPlex-7020:/opt/docker$ ls
marvyn
jd@jd-OptiPlex-7020:/opt/docker$ cd marvyn/
jd@jd-OptiPlex-7020:/opt/docker/marvyn$ ls
bin  data  etc  image  LICENSE  README.keys  README.md  services  udev
jd@jd-OptiPlex-7020:/opt/docker/marvyn$ sudo mv marvyn/opt/docker/marvyn /opt/docker/
mv: cannot stat 'marvyn/opt/docker/marvyn': No such file or directory
jd@jd-OptiPlex-7020:/opt/docker/marvyn$ cd ..
jd@jd-OptiPlex-7020:/opt/docker$ ls
marvyn
jd@jd-OptiPlex-7020:/opt/docker$ sudo mv marvyn/opt/docker/marvyn /opt/docker/
mv: cannot stat 'marvyn/opt/docker/marvyn': No such file or directory

**Comment by emmakat** [comment]
despite these errors, I am able to build the image: by running: /opt/docker/marvyn/image/build
I'll update this issue with my results.

**Comment by emmakat** [comment]
the build completed, however it's unclear what I am supposed to do next. I don't see any instructions about how to actually run the container.

**Comment by git-developer** [comment]
Well, that depends on what you plan to do. Please consider the readme, it's all documented: install, enable autorip, run.

**Comment by emmakat** [comment]
thank you! I seem to have these issues resolved.
