### ISSUE TITLE
idea for adding a step to the readme

### ISSUE THREAD

**Issue by emmakat** [git-developer/marvyn#9]
Hi again, hope you're well.
I was thinking about a PR to add a step to the readme which may help others, but I wanted to ask you first. For those of us with multiple drives, running lsscsi -g can provide useful information on the drives. I have been keeping track of things like this in https://github.com/emmakat/findopticaldrives

I could add a PR to suggest this command, in the readme on line 136 where etc/rip-disc.yml editing instructions appear. Perhaps something like:
Run ```lsscsi -g``` to confirm the optical drives and their mount locations.

**Comment by git-developer** [comment]
Sounds good!

**Comment by emmakat** [comment]
thanks! PR sent :)
